### ISSUE TITLE
MathIllegalStateException during simulation

### ISSUE THREAD

**Issue by walterxie** [alexeid/toroidalDiffusion#8]
Occasionally : 
```java
org.apache.commons.math3.exception.MathIllegalStateException: trust region step has failed to reduce Q
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.BOBYQAOptimizer.bobyqb(BOBYQAOptimizer.java:880)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.BOBYQAOptimizer.bobyqa(BOBYQAOptimizer.java:340)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.BOBYQAOptimizer.doOptimize(BOBYQAOptimizer.java:252)
	at org.apache.commons.math3.optim.nonlinear.scalar.noderiv.BOBYQAOptimizer.doOptimize(BOBYQAOptimizer.java:49)
	at org.apache.commons.math3.optim.BaseOptimizer.optimize(BaseOptimizer.java:153)
	at org.apache.commons.math3.optim.BaseMultivariateOptimizer.optimize(BaseMultivariateOptimizer.java:65)
	at org.apache.commons.math3.optim.nonlinear.scalar.MultivariateOptimizer.optimize(MultivariateOptimizer.java:63)
	at toroidaldiffusion.WrappedBivariateDiffusion.sampleByRejection(WrappedBivariateDiffusion.java:209)
	at toroidaldiffusion.PhyloWrappedBivariateDiffusion.getNewValue(PhyloWrappedBivariateDiffusion.java:241)
	at toroidaldiffusion.PhyloWrappedBivariateDiffusion.traverseTree(PhyloWrappedBivariateDiffusion.java:220)
	at toroidaldiffusion.PhyloWrappedBivariateDiffusion.traverseTree(PhyloWrappedBivariateDiffusion.java:221)
	at toroidaldiffusion.PhyloWrappedBivariateDiffusion.traverseTree(PhyloWrappedBivariateDiffusion.java:221)
	at toroidaldiffusion.PhyloWrappedBivariateDiffusion.traverseTree(PhyloWrappedBivariateDiffusion.java:221)
	at toroidaldiffusion.PhyloWrappedBivariateDiffusion.sample(PhyloWrappedBivariateDiffusion.java:157)
	at lphy.core.model.GenerativeDistribution.sample(GenerativeDistribution.java:32)
...
```

**Comment by walterxie** [comment]
Cannot calculate new value for 3.0875357245670547 and 3.2389546454267055, 
given branch length = 0.04184533374639288
mu = [4.0509262973708315, 5.1236852445169685]
sigma = [1.0298711760259887, 0.1271923963524306]
alpha = [0.75761827331078, 0.8251637431436857, 0.14751750525982674]
